### ISSUE TITLE
Compatability issue deepcopy and pybind?

### ISSUE THREAD

**Issue by HelenaKschidock** [precice/micro-manager#28]
A Dumux-Dumux coupled simulation (see [https://github.com/HelenaKschidock/macro-micro](https://github.com/HelenaKschidock/macro-micro) fails with current develop branch. Pybind was built locally using pip (after micro-manager installation).

```
(0) 21:58:31 [cplscheme::BaseCouplingScheme]:235 in advance: Time window completed
(0) 21:58:31 [impl::SolverInterfaceImpl]:464 in advance: iteration: 1 of 30, time-window: 2, time: 0.005 of 0.25, time-window-size: 0.005, max-timestep-length: 0.005, ongoing: yes, time-window-complete: yes, write-iteration-checkpoint 
Saving state of micro problem (0)
Saving state of micro problem (1)
Saving state of micro problem (2)

[...]

Saving state of micro problem (126)
Saving state of micro problem (127)
Traceback (most recent call last):
  File "/home/kschidock/FM/dumux2/dumux/dumux-adapter/build-cmake/examples/macro-micro/micro-heat/run_micro_manager.py", line 11, in <module>
    manager.solve()
  File "/home/kschidock/.local/lib/python3.10/site-packages/micro_manager/micro_manager.py", line 505, in solve
    similarity_dists, micro_sim_states = self.compute_adaptivity(similarity_dists, micro_sim_states)
  File "/home/kschidock/.local/lib/python3.10/site-packages/micro_manager/micro_manager.py", line 391, in compute_adaptivity
    micro_sim_states_n = self._adaptivity_controller.update_inactive_micro_sims(
  File "/home/kschidock/.local/lib/python3.10/site-packages/micro_manager/adaptivity.py", line 168, in update_inactive_micro_sims
    micro_sims[i] = deepcopy(micro_sims[associated_active_id])
  File "/usr/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'MicroProblem' object

```

**Comment by IshaanDesai** [comment]
The [solver dummy test](https://github.com/precice/micro-manager/actions/runs/4688301164) did not catch this error because we run the C++ solver dummy without adaptivity. We need to increase test coverage by running the solver dummies with and without adaptivity.
